name "box_setup"
maintainer "Jon Hartman"
maintainer_email "jon@focus-43.com"
license "MIT"
description "Custom cookbook for C5 Vagrant box"
version "0.01"

depends "apt"
depends "openssl"
depends "mysql"
depends "database"
depends "redis"
depends "git"
depends "apache2"
depends "nodejs"
depends "php"